routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

// RUN API [Profit keyvan gold]
Route::get('/checkOnsaleListKeyvanGold' , function(){
    Artisan::call('schedule:run');
    return 'OK';
});

/*
    دریافت لحظه ای مظنه
    به روز رسانی قیمت یک دقیقه قبل و بررسی شارپ قیمت
    ساخت قیمت های گذشته
 */
Route::namespace('Admin\CronJob')->group(function (){

    Route::get('/getOnlineAmountApi/{key}' ,'OnlineTradeController@update'); //[online Amount Trade]
    Route::get('/getPerMinuteAmount/{key}' ,'OnlineTradeController@CheckAmountPerMinute'); //[CheckPerMinute]
    Route::get('/saveChartAmount/{key}' ,'GoldAmountController@update');
    Route::get('/syncTrade/{key}' ,'SyncTradeController@update');//[Sync trade profit] 5 min

});



// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});



// API
Route::prefix('Api')->name('api.')->namespace('Api')->group(function ()
{
    // Refresh Captcha
    Route::get('refresh_captcha', 'CaptchaController@refreshCaptcha')->name('refresh_captcha');

    // Product
    Route::post('/Product','ProductController@index')->name('product');
    Route::prefix('Cart')->name('cart.')->group(function ()
    {
        Route::post('/Add','CartController@addToCart')->name('add');
        Route::get('/Remove/{id}','CartController@removecart')->name('remove');
    });

    //  Blog
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // Like AND Dislike
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');

    // LOAD Trade
    Route::post('/loadTrade','TradeController@index')->name('load.tarde');

    // ADMIN PRODUCT CATEGORY SEARCH
    Route::post('/Admin/User/search', 'UserAdminController@search')->name('admin.user.search');

});



// APP
Route::name('app.')->namespace('App')->group(function ()
{
    Route::get('/','HomeController@index')->name('home');
    Route::get('/about','AboutController@index')->name('about');
    Route::get('/other/{slug}','OtherPageController@index')->name('otherpage');
    Route::get('/cart','CartController@index')->name('cart');

    Route::get('/faq', 'FaqController@index')->name('faq');


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{slug}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });


});



// LOGIN AND LOGOUT USER
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('user')->namespace('Auth')->name('user.')->group(function () {

    Route::get('/forget', 'UserController@forgetform')->name('forget.form');
    Route::post('/forget', 'UserController@forget')->name('forget');

    Route::get('/reset/{email}', 'UserController@resetform')->name('reset.form');
    Route::post('/reset', 'UserController@reset')->name('reset');
});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('adminwebpanelkeyvangold')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@login_get_mobile')->name('login.show');
    Route::post('/login/sendCode', 'AdminController@login_send_code')->name('login.sendCode');

    Route::get('/login/verify/{mobile}', 'AdminController@login_get_code')->name('login.verify');
    Route::post('/verify', 'AdminController@login_verify')->name('login.submit');


    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');
});




// USER
Route::prefix('user')->namespace('User')->name('user.')
    ->middleware('auth')->group(function () {

        Route::get('/dashboard', 'IndexController@index')->name('dashboard');

        // USER
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/edit', 'UserController@edit')->name('edit');
            Route::put('/update/{user}', 'UserController@update')->name('update');

            Route::get('/changepassword', 'UserController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'UserController@update_passwrod')->name('update.password');

            Route::get('/verify', 'VerifyController@edit')->name('verify.edit');
            Route::post('/verify', 'VerifyController@update')->name('verify.update');
        });

        // WALLET
        Route::prefix('wallet')->name('wallet.')->group(function () {
            Route::get('/create', 'WalletController@create')->name('create');
            Route::post('/sharj', 'WalletController@sharj_wallet')->name('sharj');
        });

        // Withdrawal
        Route::prefix('withdrawal')->name('withdrawal.')->group(function () {
            Route::get('/create', 'WithdrawalController@create')->name('create');
            Route::post('/store', 'WithdrawalController@store')->name('store');
        });

        // HISTORY
        Route::get('/history', 'HistoryController@index')->name('history');

        // PAY
        Route::any('/pay', 'PayController@callBackBank')->name('pay');


        // TICKET
        Route::prefix('ticket')->name('ticket.')->group(function () {
            Route::get('/list', 'TicketController@index')->name('list');
            Route::get('/show/{ticket}', 'TicketController@show')->name('show');
            Route::get('/finished/{ticket}', 'TicketController@finished')->name('finished');
            Route::get('/add', 'TicketController@create')->name('add');
            Route::post('/store', 'TicketController@store')->name('store');
        });
        Route::prefix('conversation')->name('conversation.')->group(function () {
            Route::post('/store', 'ConversationController@store')->name('store');
        });


        // NOTIFICATION
        Route::prefix('notification')->name('notification.')->group(function () {
            Route::get('/list', 'NotificationController@index')->name('list');
            Route::get('/show/{notification}', 'NotificationController@show')->name('show');

        });



        // PORTFO
        Route::prefix('portfo')->name('portfo.')->group(function () {
            Route::get('/list', 'PortfoController@index')->name('list');
            Route::post('/store', 'PortfoController@store')->name('store');
            Route::get('/close/{portfo}', 'PortfoController@close')->name('close');
        });


        // CREATE TRADE
        Route::prefix('tradelist')->name('tradelist.')->group(function () {
            Route::get('/list', 'TradeListController@index')->name('list');
            Route::post('/store/{type}', 'TradeListController@store')->name('store');
            Route::get('/destroy/{id}', 'TradeListController@destroy')->name('destroy');
        });


        // DO TRADE
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::get('/', 'TradeController@tradeList')->name('tradeList');
            Route::get('/list/{portfo}', 'TradeController@index')->name('list');
            Route::post('/store/{tradeList}', 'TradeController@store')->name('store');
            Route::get('/close', 'CloseTradeController@CloseSystemTrade')->name('close');
            Route::get('/video', 'LearnController@index')->name('video');
        });


    });



// ADMIN
Route::prefix('adminwebpanelkeyvangold')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {

        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ close trade *************
        Route::get('/closeTrade', 'CloseTradeController@closeTrade')->middleware('permission:permission_trade_setting')->name('closeTrade');


        //************ portfo trade admin *************
        Route::prefix('portfo')->name('portfo.')->middleware('permission:permission_portfo')->group(function () {
            Route::any('/list', 'PortfoController@index')->name('list');
            Route::get('/trade/{portfo}', 'PortfoController@trade')->name('show');
        });


        //************ portfo trade admin *************
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::any('/list', 'TradeController@index')->middleware('permission:permission_trade')->name('list');
            Route::get('/onsale', 'TradeController@onSale')->middleware('permission:permission_onSale')->name('onsale');
        });


        //************ online trade setting admin *************

resources/views/app/page/about.blade.php
@extends('app.index')

@section('canonical',\Request::url())

@section('ogtag')
    <meta property="og:type" content="Website" />
@endsection

@section('title',isset($response['meta']['title']) ?
            $response['meta']['title'] : 'درباره ما' )

@section('keywords',isset($response['meta']['keyword']) ?
            $response['meta']['keyword'] : $response['app_issue'])

@section('description',isset($response['meta']['description']) ?
            $response['meta']['description'] : $response['app_issue'])

@section('content')



    <section class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="font-size-14 text-center text-black font-weight-bold mt-4">درباره ما</h2>
                    <hr class="divider"/>
                    <div class="font-yekan font-size-14 line-35 text-justify">
                        {!! $response['app_description'] !!}
                    </div>
                </div>

                <div class="col-12">
                    <h2 class="font-size-14 text-center text-black font-weight-bold mt-4">آدرس</h2>
                    <hr class="divider"/>
                    <div class="font-yekan font-size-14 line-35 text-center">
                        {!! $response['app_address'] !!}
                    </div>
                </div>

                <div class="col-12">
                    <h2 class="font-size-14 text-center text-black font-weight-bold mt-4">تلفن تماس</h2>
                    <hr class="divider"/>
                    <div class="font-yekan font-size-14 line-35 text-center mx-auto">
                            @foreach(explode ("-", $response['app_tell']) as $tell)
                                    <a class="text-dark decoration-none font-size-14 fa-num "
                                       href="tel:{{$tell}}">
                                        &nbsp;  {{$tell}} |
                                    </a>
                            @endforeach

                    </div>
                </div>

            </div>
        </div>
    </section>



@endsection

@section('script')
    <script>

        $("#product-carousel").owlCarousel({
            loop: true,
            autoplay: true,
            items: 3,
            rtl: true,
            center: true,
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
    </script>
@endsection

resources/views/app/page/cart.blade.php
@extends('app.index')

@section('title','سبد خرید شما')

@section('content')


    <section class="page-section">
        <div class="container text-center">
            <h2 class="font-yekan font-weight-bold font-size-22">سبد خرید شما</h2>
            <hr class="divider mb-5">
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12 mx-auto">
                    @if(session()->get('cart'))
                        <table class="table table-striped table-bordered text-center">
                            <tr>
                                <th>حذف</th>
                                <th>نام محصول</th>
                                <th>وزن</th>
                                <th>قیمت</th>
                            </tr>
                            @foreach(session()->get('cart') as $cart)
                                <tr>
                                    <td>
                                        <a class="decoration-none" href="{{route('api.cart.remove',$cart['id'])}}"><i class="fa fa-times text-danger"></i></a>
                                    </td>
                                    <td class="font-yekan font-size-14 text-primary font-weight-bold">
                                        {{$cart['title']}}
                                    </td>
                                    <td class="fa-num font-size-14 text-danger font-weight-bold">
                                        {{$cart['weight']}} گرم
                                    </td>
                                    <td class="fa-num font-size-14 text-success font-weight-bold">
                                        {{number_format($cart['price'])}} تومان
                                    </td>
                                </tr>
                            @endforeach
                            <tr>
                                <td>جمع کل</td>
                                <td colspan="3" class="fa-num font-weight-bold text-info">
                                    {{number_format($response['sum'])}}تومان
                                </td>
                            </tr>
                        </table>

                        <a class="btn btn-success btn-sm font-yekan font-size-14 text-decoration-none my-4"
                           href="#">پرداخت انلاین و خرید محصول</a>
                    @else
                        <div class="alert alert-warning">متاسفانه سبد خرید شما خالی می باشد</div>
                    @endif
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/app/page/faq.blade.php
@extends('app.index')

@section('title','سوالات متداول')

@section('content')


    <!-- FAQ -->
    <section class="page-section">
        <div class="container">

            @foreach($response['question'] as $category => $questions)
                <div class="row justify-content-center">
                    <div class="col-lg-10 text-center">
                        <div class="row mb-4">
                            <div class="accordion col-12">
                                <h2 class="font-size-14 bg-gold p-2 border-radius-5 font-weight-bold">
                                    {{$questions[0]->Category->title}}
                                </h2>
                                @foreach($questions as $question)
                                    <div class="card border">
                                        <div class="card-header py-1" id="question">
                                            <h2 class="align-right mb-0">
                                                <button
                                                    class="btn btn-link text-dark font-family-yekan align-right
                                                            font-weight-bold font-size-13 decoration-none collapsed"
                                                    data-toggle="collapse" data-target="#question{{$question->id}}"
                                                    aria-expanded="false" aria-controls="question{{$question->id}}">
                                                    {{$question->question}}
                                                </button>
                                                <i class="fas fa-plus float-left font-size-22 mt-2 text-gold"></i>
                                            </h2>
                                        </div>
                                        <div id="question{{$question->id}}" class="align-right direction-rtl collapse"
                                             aria-labelledby="question{{$question->id}}">
                                            <div class="card-body font-family-yekan font-size-13 mx-2 text-justify py-3 direction-rtl">
                                                {{$question->answer}}
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach

        </div>
    </section>

@endsection

resources/views/app/page/home.blade.php
@extends('app.index')

@section('canonical',\Request::url())

@section('ogtag')
    <meta property="og:type" content="Website" />
@endsection

@section('title',isset($response['meta']['title']) ?
            $response['meta']['title'] : $response['app_name'] )

@section('keywords',isset($response['meta']['keyword']) ?
            $response['meta']['keyword'] : $response['app_issue'])

@section('description',isset($response['meta']['description']) ?
            $response['meta']['description'] : $response['app_issue'])

@section('content')


    <!-- MASTHEAD -->
    <header class="masthead border-top-main">
        <div class="container h-100">
            <div class="row justify-content-center text-center">
                <div class="col-lg-10 mt-2">

                </div>

            </div>
        </div>
    </header>


    <!-- PHYSICAL TABLE -->
    {{--    <section class="page-section d-none">--}}
{{--        <div class="container-fluid text-center">--}}
{{--            <div class="row">--}}
{{--                <div class="col-12 text-center">--}}
{{--                    <h2 class="font-size-19 font-weight-bold">خرید و فروش نقدی</h2>--}}
{{--                    <hr class="divider">--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="row mx-0 mx-xl-5 mx-lg-5">--}}
{{--                <div class="col-md-6 border rounded p-3">--}}
{{--                    <h2 class="font-yekan font-weight-bold font-size-15 mt-3 text-primary">لیست خریداران</h2>--}}
{{--                    <hr class="divider mb-1">--}}
{{--                    <div class="table-responsive user-div-table mt-3">--}}
{{--                        <table class="table table-bordered table-striped">--}}
{{--                            <tr class="bg-primary text-white">--}}
{{--                                <td class="font-size-13">کد</td>--}}
{{--                                <td class="font-size-13">واحد</td>--}}
{{--                                <td class="font-size-13">مظنه(تومان)</td>--}}
{{--                                <td class="font-size-13">معامله</td>--}}
{{--                            </tr>--}}
{{--                            <tbody>--}}
{{--                            @foreach($response['buyer'] as $buyer)--}}
{{--                                <tr class="text-center font-size-13">--}}
{{--                                    <td class="user-danger">{{$buyer->id}}</td>--}}
{{--                                    <td class="user-black">{{number_format($buyer->weight)}}</td>--}}
{{--                                    <td class="user-black">{{number_format($buyer->amount)}}</td>--}}
{{--                                    <td>--}}
{{--                                        <a href="{{route('user.order.add',$buyer->id)}}" class="btn btn-outline-primary btn-sm font-yekan font-size-14"> معامله</a>--}}
{{--                                    </td>--}}
{{--                                </tr>--}}
{{--                            @endforeach--}}
{{--                            </tbody>--}}
{{--                        </table>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="col-md-6 border rounded p-3">--}}
{{--                    <h2 class="font-yekan font-weight-bold font-size-15 mt-3 text-danger">لیست فروشندگان</h2>--}}
{{--                    <hr class="divider mb-1">--}}
{{--                    <div class="table-responsive user-div-table mt-3 ">--}}
{{--                            <table class="table table-striped table-bordered border">--}}
{{--                                <tr class="font-size-13 text-white bg-danger">--}}
{{--                                    <td class="font-size-13">کد</td>--}}
{{--                                    <td class="font-size-13">واحد</td>--}}
{{--                                    <td class="font-size-13">مظنه(تومان)</td>--}}
{{--                                    <td class="font-size-13">معامله</td>--}}
{{--                                </tr>--}}
{{--                                <tbody>--}}
{{--                                @foreach($response['seller'] as $seller)--}}
{{--                                    <tr class="text-center font-size-13">--}}
{{--                                        <td class="user-danger">{{$seller->id}}</td>--}}
{{--                                        <td class="user-black">{{number_format($seller->weight)}}</td>--}}
{{--                                        <td class="user-black">{{number_format($seller->amount)}}</td>--}}
{{--                                        <td>--}}
{{--                                            <a href="{{route('user.order.add',$seller->id)}}" class="btn btn-outline-danger btn-sm font-yekan font-size-14"> معامله</a>--}}
{{--                                        </td>--}}
{{--                                    </tr>--}}
{{--                                @endforeach--}}
{{--                                </tbody>--}}
{{--                            </table>--}}
{{--                        </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </section>--}}


    <!-- INFO  -->


    <section class="page-section" style="background: #f8f7f7">
        <div class="container">

            <div class="row">
                <div class="col-12 text-center mx-auto">
                    <h2 class="font-yekan font-size-15 font-weight-bold text-center mt-3">{{$response['help']->title}}</h2>
                    <hr class="divider"/>
                </div>
            </div>
            <div class="row my-2">

                <div class="col-md-5">
                    <img src="{{url('app/img/help.jpg')}}" alt="{{$response['help']->title}}" class="img-fluid rounded">
                </div>
                <div class="col-md-7">
                    <article class="font-yekan font-size-14 line-35 text-justify direction-rtl">
                        {!! mb_substr( $response['help']->content,0,1000 ) !!} ...
                    </article>
                    <a href="{{route('app.otherpage','راهنمای-خرید')}}"
                       class="btn btn-outline-info btn-sm font-size-13 my-3">مشاهده ادامه مطلب</a>
                </div>
            </div>

        </div>
    </section>


    <!-- PRODUCT -->
    <section class="page-section blog mx-auto text-center">
        <div class="container pos-z-index">
            <h2 class="font-yekan font-weight-bold font-size-22">نمونه کارها</h2>
            <hr class="divider mb-1">
            <div class="tabs my-4">
                <a class="blog_group cursor-pointer font-size-12 font-weight-bold active" onclick="loadProduct(this,'all')">همه</a>

                @foreach($response['product_category'] as $category)
                    <a class="blog_group cursor-pointer font-size-12 font-weight-bold" onclick="loadProduct(this,{{$category->id}})">
                        {{$category->title}}
                    </a>
                @endforeach
            </div>

            <div id="product-view">
                <div class="carousel owl-carousel" id="product-carousel">
                    @foreach($response['product'] as $product)
                        <div class="item border border-warning rounded mx-1">
                              <img src="{{url($product->poster)}}" alt="{{$product->title}}"
                                         class="img-fluid" style="height: 260px;width: 320px">
                              <h2 class="title pt-3 border-top border-warning bg-light">{{$product->title}}</h2>
                        </div>
                    @endforeach
                </div>
            </div>

        </div>
    </section>



    <!-- BLOG -->
    @if(isset($response['blog_groups']) && count($response['blog_groups']) > 0 )
        <section class="blog mb-5" style="background: #f8f7f7">
            <div class="container pos-z-index">
                <div class="row mb-4">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <h3 class="text-center mt-5 font-size-22 font-yekan font-weight-bold">بلاگ</h3>
                        <hr class="divider mb-1">
                    </div>
                </div>
                <div class="tabs">
                    @php $active='active' @endphp
                    @foreach($response['blog_groups'] as $bloggroup)
                        <a class="{{$active}} blog_group cursor-pointer" onclick="loadBlog(this,{{$bloggroup->id}})">{{$bloggroup->title}}</a>
                        @php $active='' @endphp
                    @endforeach
                </div>

                <div id="blogs-view">
                    <div class="carousel owl-carousel" id="blog-carousel">
                        @foreach($response['blogs'] as $blog)
                            <div class="item">
                                <a href="{{route('app.blog.show',$blog->slug)}}" class="text-decoration-none">
                                    <figure>
                                        <img src="{{url($blog->thumbnail)}}" alt="{{$blog->title}}">
                                    </figure>
                                    <h2 class="title text-center" style="min-height: 40px">{{$blog->title}}</h2>
                                    <p class="desc text-justify" style="min-height: 80px">
                                        {!! mb_substr(strip_tags($blog->content),0,140,'UTF8') !!}...
                                    </p>
                                    <div class="fa-num direction-ltr text-black font-size-14 font-weight-bold">
                                        {{jdate($blog->created_at)->format('Y %B')}}
                                    </div>
                                </a>
                            </div>
                        @endforeach
                    </div>
                </div>

            </div>
        </section>
    @endif


@endsection

@section('script')
    <script>

        $("#product-carousel").owlCarousel({
            loop: false,
            autoplay: false,
            items: 5,
            rtl:true,
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
        $("#blog-carousel").owlCarousel({
            margin: 40,
            loop: true,
            autoplay: true,
            items: 4,
            rtl: true,
            responsive: {
                0: {
                    items: 1
                },
                500: {
                    items: 2
                },
                800: {
                    items: 3
                },
                1000: {
                    items: 4
                }
            }
        });


    </script>
@endsection

resources/views/app/page/page.blade.php
@extends('app.index')

@section('canonical',\Request::url())

@section('ogtag')
    <meta property="og:type" content="Website" />
@endsection

@section('title',isset($response['meta']['title']) ?
            $response['meta']['title'] : $response['page']->title )

@section('keywords',isset($response['meta']['keyword']) ?
            $response['meta']['keyword'] : $response['app_issue'])

@section('description',isset($response['meta']['description']) ?
            $response['meta']['description'] : $response['app_issue'])

@section('content')




    <section class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-3">
                    <img src="{{$response['page']->thumbnail}}" alt="{{$response['page']->title}}" class="img-fluid rounded">
                </div>
                <div class="col-12">
                    <h2 class="font-size-19 text-center text-black font-weight-bold mt-5">
                        {{$response['page']->title}}
                    </h2>
                    <hr class="divider"/>
                    <div class="font-yekan font-size-14 line-35 text-justify">
                        {!! $response['page']->content !!}
                    </div>
                </div>



            </div>
        </div>
    </section>



@endsection

@section('script')
    <script>

        $("#product-carousel").owlCarousel({
            loop: true,
            autoplay: true,
            items: 3,
            rtl: true,
            center: true,
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
    </script>
@endsection