routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

// RUN API [Profit keyvan gold]
Route::get('/checkOnsaleListKeyvanGold' , function(){
    Artisan::call('schedule:run');
    return 'OK';
});

/*
    دریافت لحظه ای مظنه
    به روز رسانی قیمت یک دقیقه قبل و بررسی شارپ قیمت
    ساخت قیمت های گذشته
 */
Route::namespace('Admin\CronJob')->group(function (){

    Route::get('/getOnlineAmountApi/{key}' ,'OnlineTradeController@update'); //[online Amount Trade]
    Route::get('/getPerMinuteAmount/{key}' ,'OnlineTradeController@CheckAmountPerMinute'); //[CheckPerMinute]
    Route::get('/saveChartAmount/{key}' ,'GoldAmountController@update');
    Route::get('/syncTrade/{key}' ,'SyncTradeController@update');//[Sync trade profit] 5 min

});



// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});



// API
Route::prefix('Api')->name('api.')->namespace('Api')->group(function ()
{
    // Refresh Captcha
    Route::get('refresh_captcha', 'CaptchaController@refreshCaptcha')->name('refresh_captcha');

    // Product
    Route::post('/Product','ProductController@index')->name('product');
    Route::prefix('Cart')->name('cart.')->group(function ()
    {
        Route::post('/Add','CartController@addToCart')->name('add');
        Route::get('/Remove/{id}','CartController@removecart')->name('remove');
    });

    //  Blog
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // Like AND Dislike
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');

    // LOAD Trade
    Route::post('/loadTrade','TradeController@index')->name('load.tarde');

    // ADMIN PRODUCT CATEGORY SEARCH
    Route::post('/Admin/User/search', 'UserAdminController@search')->name('admin.user.search');

});



// APP
Route::name('app.')->namespace('App')->group(function ()
{
    Route::get('/','HomeController@index')->name('home');
    Route::get('/about','AboutController@index')->name('about');
    Route::get('/other/{slug}','OtherPageController@index')->name('otherpage');
    Route::get('/cart','CartController@index')->name('cart');

    Route::get('/faq', 'FaqController@index')->name('faq');


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{slug}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });


});



// LOGIN AND LOGOUT USER
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('user')->namespace('Auth')->name('user.')->group(function () {

    Route::get('/forget', 'UserController@forgetform')->name('forget.form');
    Route::post('/forget', 'UserController@forget')->name('forget');

    Route::get('/reset/{email}', 'UserController@resetform')->name('reset.form');
    Route::post('/reset', 'UserController@reset')->name('reset');
});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('adminwebpanelkeyvangold')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@login_get_mobile')->name('login.show');
    Route::post('/login/sendCode', 'AdminController@login_send_code')->name('login.sendCode');

    Route::get('/login/verify/{mobile}', 'AdminController@login_get_code')->name('login.verify');
    Route::post('/verify', 'AdminController@login_verify')->name('login.submit');


    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');
});




// USER
Route::prefix('user')->namespace('User')->name('user.')
    ->middleware('auth')->group(function () {

        Route::get('/dashboard', 'IndexController@index')->name('dashboard');

        // USER
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/edit', 'UserController@edit')->name('edit');
            Route::put('/update/{user}', 'UserController@update')->name('update');

            Route::get('/changepassword', 'UserController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'UserController@update_passwrod')->name('update.password');

            Route::get('/verify', 'VerifyController@edit')->name('verify.edit');
            Route::post('/verify', 'VerifyController@update')->name('verify.update');
        });

        // WALLET
        Route::prefix('wallet')->name('wallet.')->group(function () {
            Route::get('/create', 'WalletController@create')->name('create');
            Route::post('/sharj', 'WalletController@sharj_wallet')->name('sharj');
        });

        // Withdrawal
        Route::prefix('withdrawal')->name('withdrawal.')->group(function () {
            Route::get('/create', 'WithdrawalController@create')->name('create');
            Route::post('/store', 'WithdrawalController@store')->name('store');
        });

        // HISTORY
        Route::get('/history', 'HistoryController@index')->name('history');

        // PAY
        Route::any('/pay', 'PayController@callBackBank')->name('pay');


        // TICKET
        Route::prefix('ticket')->name('ticket.')->group(function () {
            Route::get('/list', 'TicketController@index')->name('list');
            Route::get('/show/{ticket}', 'TicketController@show')->name('show');
            Route::get('/finished/{ticket}', 'TicketController@finished')->name('finished');
            Route::get('/add', 'TicketController@create')->name('add');
            Route::post('/store', 'TicketController@store')->name('store');
        });
        Route::prefix('conversation')->name('conversation.')->group(function () {
            Route::post('/store', 'ConversationController@store')->name('store');
        });


        // NOTIFICATION
        Route::prefix('notification')->name('notification.')->group(function () {
            Route::get('/list', 'NotificationController@index')->name('list');
            Route::get('/show/{notification}', 'NotificationController@show')->name('show');

        });



        // PORTFO
        Route::prefix('portfo')->name('portfo.')->group(function () {
            Route::get('/list', 'PortfoController@index')->name('list');
            Route::post('/store', 'PortfoController@store')->name('store');
            Route::get('/close/{portfo}', 'PortfoController@close')->name('close');
        });


        // CREATE TRADE
        Route::prefix('tradelist')->name('tradelist.')->group(function () {
            Route::get('/list', 'TradeListController@index')->name('list');
            Route::post('/store/{type}', 'TradeListController@store')->name('store');
            Route::get('/destroy/{id}', 'TradeListController@destroy')->name('destroy');
        });


        // DO TRADE
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::get('/', 'TradeController@tradeList')->name('tradeList');
            Route::get('/list/{portfo}', 'TradeController@index')->name('list');
            Route::post('/store/{tradeList}', 'TradeController@store')->name('store');
            Route::get('/close', 'CloseTradeController@CloseSystemTrade')->name('close');
            Route::get('/video', 'LearnController@index')->name('video');
        });


    });



// ADMIN
Route::prefix('adminwebpanelkeyvangold')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {

        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ close trade *************
        Route::get('/closeTrade', 'CloseTradeController@closeTrade')->middleware('permission:permission_trade_setting')->name('closeTrade');


        //************ portfo trade admin *************
        Route::prefix('portfo')->name('portfo.')->middleware('permission:permission_portfo')->group(function () {
            Route::any('/list', 'PortfoController@index')->name('list');
            Route::get('/trade/{portfo}', 'PortfoController@trade')->name('show');
        });


        //************ portfo trade admin *************
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::any('/list', 'TradeController@index')->middleware('permission:permission_trade')->name('list');
            Route::get('/onsale', 'TradeController@onSale')->middleware('permission:permission_onSale')->name('onsale');
        });


        //************ online trade setting admin *************

resources/views/app/top/header.blade.php
<!-- FIRST NAV -->
<div class="container-fluid bg-gold py-1">
    <div class="row direction-ltr">
        <div class="col-xl-6 col-lg-6 col-md-6 col-xs-12 col-sm-12 text-xl-left text-lg-left text-md-left text-center direction-ltr">
                <span>
                    <a href="mailto:info@keivangold.ir" class="decoration-none font-size-11 font-weight-bold text-dark" data-toggle="tooltip" title="ایمیل" data-placement="bottom">
                        <i class="orange-color fa fa-envelope my-2"></i>&nbsp;
                        info@keivangold.ir
                    </a>
                </span>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-6 col-xs-12 col-sm-12  text-xl-right text-lg-right text-md-right text-center ">
            &nbsp;<span class="mb-2 fa-num font-size-11 font-weight-bold text-dark">{{jdate()->format('%A, %d %B %y')}}</span>
        </div>
    </div>
</div>

<!-- LOGO -->
<div class="container-fluid  direction-ltr"
     style="background-image: url(app/img/banner.jpg)!important">

    <div class="row text-center py-2">
        <img src="{{url('app/img/logo.png')}}"  class="img-fluid mx-auto" alt="">
    </div>

</div>


<div class="container-fluid sticky-top">
    <!-- MENU -->
    <div class="row sticky-top">

        <!-- MENU DESKTOP -->
        <nav class="navbar navbar-expand-lg w-100 p-0 m-0 border-bottom-red direction-ltr d-none d-lg-block" id="blogNav">
            <div class="container-fluid">

                <div id="search_div">
                    @auth
                        <a href="{{route('login')}}" class="btn btn-warning btn-sm text-black">
                            {{\Illuminate\Support\Facades\Auth::user()->name . ' عزیز خوش آمدید '}}
                        </a>
                    @else
                        <a href="https://keivangold.ir/login" class="btn btn-warning btn-sm text-black">ورود | ثبت نام</a>
                    @endauth

                </div>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0 direction-rtl">

                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.home')}}"> صفحه اصلی</a>
                        </li>

                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr text-gold font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.otherpage','راهنمای-خرید-و-فروش-لحظه-ای')}}"> راهنمای خرید و فروش  نقدی</a>
                        </li>


                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.blog.home','آموزش')}}">مطالب آموزشی</a>
                        </li>
                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.blog.home')}}">بلاگ</a>
                        </li>

                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.faq')}}">سوالات متداول</a>
                        </li>

                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="{{route('app.about')}}">درباره ما</a>
                        </li>
                        <li class="nav-item align-right">
                            <a class="nav-link js-scroll-trigger font-family-yekan direction-ltr font-size-14 font-weight-normal menu-blog my-2" href="#footer">تماس با ما</a>
                        </li>

                    </ul>
                </div>

            </div>
        </nav>
        <!-- MENU DESKTOP -->

        <!-- MENU MOBILE -->
        <div class="col-12 d-block d-lg-none bg-blog-main direction-rtl">
            <div class="d-flex justify-content-between position-relative d-md-none d-block p-1">

                <button class="menuBtn btn " onclick="openMenu()" >
                    <i class="fas fa-bars font-size-22 color-blog-secondary bold"></i>
                </button>

                <div class="d-inline-block mx-auto mt-2">
                    <a href="{{route('app.blog.home')}}" class="font-family-yekan text-decoration-none  font-size-14  font-weight-bold color-blog-secondary">{{ $response['app_name']}}</a>
                </div>

                <button class="bg-transparent border-none shadow-none" id="search_btn" onclick="openSearchMobile()">
                    <i class="fa fa-search color-blog-secondary"></i>
                </button>
            </div>

            <nav class="mainNav" id="mobileMenu">
                <div class="mb-5 d-flex d-md-none w-100 justify-content-between align-items-center">
                    <a href="{{route('app.blog.home')}}" class="font-family-yekan text-decoration-none text-white font-size-17 font-weight-bold">
                        <img src=" {{url($response['app_logo'])}}" height="50px">
                    </a>
                    <button class="close font-38" onclick="openMenu()">
                        <i class="fas fa-times text-white"></i>
                    </button>
                </div>

                <ul class="list-unstyled bold">

                    <li>
                        @auth
                            <a href="{{route('login')}}" class="btn btn-warning btn-sm text-black">
                                {{\Illuminate\Support\Facades\Auth::user()->name . ' عزیز خوش آمدید '}}
                            </a>
                        @else
                            <a href="{{route('login')}}" class="btn btn-warning btn-sm text-black">ورود | ثبت نام</a>
                        @endauth
                    </li>

                    <li>
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="{{route('app.home')}}"> صفحه اصلی</a>
                    </li>

                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 text-gold text-decoration-none" href="{{route('app.otherpage','راهنمای-خرید-و-فروش-لحظه-ای')}}"> راهنمای خرید و فروش نقدی</a>
                    </li>

                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="{{route('app.blog.home','آموزش')}}">مطالب آموزشی</a>
                    </li>

                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="{{route('app.blog.home')}}">بلاگ</a>
                    </li>

                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="{{route('app.faq')}}">سوالات متداول</a>
                    </li>

                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="{{route('app.about')}}">درباره ما</a>
                    </li>
                    <li class="nav-item align-right">
                        <a class="direction-ltr font-family-yekan font-weight-normal font-size-14 color-blog-secondary text-decoration-none" href="#footer">تماس با ما</a>
                    </li>
                </ul>
            </nav>

            <div class="mainNav" id="mobileSearch">

                <div class="mb-5 d-flex d-md-none w-100 justify-content-between align-items-center">
                    <button class="close font-size-36" onclick="openSearchMobile()">
                        <i class="fas fa-times text-white"></i>
                    </button>
                </div>

                <div class="row">
                    <div class="col-11 search_form m-0 p-0" id="search_box_id">
                        <form action="{{route('app.blog.search')}}" method="post" class="mr-2">
                            @csrf
                            <h2 class="font-size-14 text-white text-center mb-4 font-family-yekan">جستجو</h2>
                            <input type="text" style="height: 34px!important;"
                                   class="form-control text-right font-family-iransans font-size-11
                                       shadow-none direction-rtl text-white border-bottom border-top-0 border-left-0 border-right-0 rounded-0 bg-black" autocomplete="off"
                                   onkeyup="suggest_search_blog_mobile()" id="search_text_mobile_id" name="search_text_name">
                            <div class="mt-3 pt-3 direction-rtl" id="aj_search_content_mobile">

                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>
        <!-- MENU MOBILE -->

    </div>
</div>