routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

// RUN API [Profit keyvan gold]
Route::get('/checkOnsaleListKeyvanGold' , function(){
    Artisan::call('schedule:run');
    return 'OK';
});

/*
    دریافت لحظه ای مظنه
    به روز رسانی قیمت یک دقیقه قبل و بررسی شارپ قیمت
    ساخت قیمت های گذشته
 */
Route::namespace('Admin\CronJob')->group(function (){

    Route::get('/getOnlineAmountApi/{key}' ,'OnlineTradeController@update'); //[online Amount Trade]
    Route::get('/getPerMinuteAmount/{key}' ,'OnlineTradeController@CheckAmountPerMinute'); //[CheckPerMinute]
    Route::get('/saveChartAmount/{key}' ,'GoldAmountController@update');
    Route::get('/syncTrade/{key}' ,'SyncTradeController@update');//[Sync trade profit] 5 min

});



// CLEAR CACHE
Route::prefix('cache')->group(function (){
    Route::get('/config', function () {
        $exit_code = Artisan::call('config:cache');
        return 'true';
    });
    Route::get('/view', function () {
        $exit_code = Artisan::call('view:cache');
        return 'true';
    });
    Route::get('/clear', function () {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });
});



// API
Route::prefix('Api')->name('api.')->namespace('Api')->group(function ()
{
    // Refresh Captcha
    Route::get('refresh_captcha', 'CaptchaController@refreshCaptcha')->name('refresh_captcha');

    // Product
    Route::post('/Product','ProductController@index')->name('product');
    Route::prefix('Cart')->name('cart.')->group(function ()
    {
        Route::post('/Add','CartController@addToCart')->name('add');
        Route::get('/Remove/{id}','CartController@removecart')->name('remove');
    });

    //  Blog
    Route::post('/loadBlog','BlogController@blogGroups')->name('load.blog');
    Route::post('/Blog/search', 'BlogController@search')->name('blog.search');

    // Like AND Dislike
    Route::post('/Comment/like', 'CommentController@like')->name('comment.like');
    Route::post('/Comment/dislike', 'CommentController@dislike')->name('comment.dislike');

    // LOAD Trade
    Route::post('/loadTrade','TradeController@index')->name('load.tarde');

    // ADMIN PRODUCT CATEGORY SEARCH
    Route::post('/Admin/User/search', 'UserAdminController@search')->name('admin.user.search');

});



// APP
Route::name('app.')->namespace('App')->group(function ()
{
    Route::get('/','HomeController@index')->name('home');
    Route::get('/about','AboutController@index')->name('about');
    Route::get('/other/{slug}','OtherPageController@index')->name('otherpage');
    Route::get('/cart','CartController@index')->name('cart');

    Route::get('/faq', 'FaqController@index')->name('faq');


    // BLOG
    Route::prefix('blog+')->name('blog.')->group(function ()
    {
        Route::get('/{slug?}', 'BlogController@index')->name('home');
        Route::get('/article/{slug}', 'BlogController@show')->name('show');
        Route::post('/search', 'BlogController@search')->name('search');
        Route::post('/comment/store', 'CommentController@store')->name('comment.store');
    });


});



// LOGIN AND LOGOUT USER
Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('user')->namespace('Auth')->name('user.')->group(function () {

    Route::get('/forget', 'UserController@forgetform')->name('forget.form');
    Route::post('/forget', 'UserController@forget')->name('forget');

    Route::get('/reset/{email}', 'UserController@resetform')->name('reset.form');
    Route::post('/reset', 'UserController@reset')->name('reset');
});



// LOGIN ADMIN
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::prefix('adminwebpanelkeyvangold')->namespace('Auth')->name('admin.')->group(function ()
{
    Route::get('/login', 'AdminController@login_get_mobile')->name('login.show');
    Route::post('/login/sendCode', 'AdminController@login_send_code')->name('login.sendCode');

    Route::get('/login/verify/{mobile}', 'AdminController@login_get_code')->name('login.verify');
    Route::post('/verify', 'AdminController@login_verify')->name('login.submit');


    Route::get('/forget', 'AdminController@forgetform')->name('forget.form');
    Route::post('/forget', 'AdminController@forget')->name('forget');

    Route::get('/reset/{email}', 'AdminController@resetform')->name('reset.form');
    Route::post('/reset', 'AdminController@reset')->name('reset');
});




// USER
Route::prefix('user')->namespace('User')->name('user.')
    ->middleware('auth')->group(function () {

        Route::get('/dashboard', 'IndexController@index')->name('dashboard');

        // USER
        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/edit', 'UserController@edit')->name('edit');
            Route::put('/update/{user}', 'UserController@update')->name('update');

            Route::get('/changepassword', 'UserController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'UserController@update_passwrod')->name('update.password');

            Route::get('/verify', 'VerifyController@edit')->name('verify.edit');
            Route::post('/verify', 'VerifyController@update')->name('verify.update');
        });

        // WALLET
        Route::prefix('wallet')->name('wallet.')->group(function () {
            Route::get('/create', 'WalletController@create')->name('create');
            Route::post('/sharj', 'WalletController@sharj_wallet')->name('sharj');
        });

        // Withdrawal
        Route::prefix('withdrawal')->name('withdrawal.')->group(function () {
            Route::get('/create', 'WithdrawalController@create')->name('create');
            Route::post('/store', 'WithdrawalController@store')->name('store');
        });

        // HISTORY
        Route::get('/history', 'HistoryController@index')->name('history');

        // PAY
        Route::any('/pay', 'PayController@callBackBank')->name('pay');


        // TICKET
        Route::prefix('ticket')->name('ticket.')->group(function () {
            Route::get('/list', 'TicketController@index')->name('list');
            Route::get('/show/{ticket}', 'TicketController@show')->name('show');
            Route::get('/finished/{ticket}', 'TicketController@finished')->name('finished');
            Route::get('/add', 'TicketController@create')->name('add');
            Route::post('/store', 'TicketController@store')->name('store');
        });
        Route::prefix('conversation')->name('conversation.')->group(function () {
            Route::post('/store', 'ConversationController@store')->name('store');
        });


        // NOTIFICATION
        Route::prefix('notification')->name('notification.')->group(function () {
            Route::get('/list', 'NotificationController@index')->name('list');
            Route::get('/show/{notification}', 'NotificationController@show')->name('show');

        });



        // PORTFO
        Route::prefix('portfo')->name('portfo.')->group(function () {
            Route::get('/list', 'PortfoController@index')->name('list');
            Route::post('/store', 'PortfoController@store')->name('store');
            Route::get('/close/{portfo}', 'PortfoController@close')->name('close');
        });


        // CREATE TRADE
        Route::prefix('tradelist')->name('tradelist.')->group(function () {
            Route::get('/list', 'TradeListController@index')->name('list');
            Route::post('/store/{type}', 'TradeListController@store')->name('store');
            Route::get('/destroy/{id}', 'TradeListController@destroy')->name('destroy');
        });


        // DO TRADE
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::get('/', 'TradeController@tradeList')->name('tradeList');
            Route::get('/list/{portfo}', 'TradeController@index')->name('list');
            Route::post('/store/{tradeList}', 'TradeController@store')->name('store');
            Route::get('/close', 'CloseTradeController@CloseSystemTrade')->name('close');
            Route::get('/video', 'LearnController@index')->name('video');
        });


    });



// ADMIN
Route::prefix('adminwebpanelkeyvangold')->namespace('Admin')->name('admin.')
    ->middleware('auth:admin')->group(function () {

        Route::get('/', 'IndexController@index')->name('dashboard');


        //************ admin  *************
        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/edit', 'AdminController@edit')->name('edit');
            Route::put('/update/{user}', 'AdminController@update')->name('update');

            Route::get('/changepassword', 'AdminController@edit_passwrod')->name('edit.password');
            Route::put('/updatepassword', 'AdminController@update_passwrod')->name('update.password');
        });


        //************ close trade *************
        Route::get('/closeTrade', 'CloseTradeController@closeTrade')->middleware('permission:permission_trade_setting')->name('closeTrade');


        //************ portfo trade admin *************
        Route::prefix('portfo')->name('portfo.')->middleware('permission:permission_portfo')->group(function () {
            Route::any('/list', 'PortfoController@index')->name('list');
            Route::get('/trade/{portfo}', 'PortfoController@trade')->name('show');
        });


        //************ portfo trade admin *************
        Route::prefix('trade')->name('trade.')->group(function () {
            Route::any('/list', 'TradeController@index')->middleware('permission:permission_trade')->name('list');
            Route::get('/onsale', 'TradeController@onSale')->middleware('permission:permission_onSale')->name('onsale');
        });


        //************ online trade setting admin *************

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\Export;
use App\Http\Controllers\Controller;
use App\Models\Pay;
use App\Models\Portfo;
use App\Models\Setting;
use App\Models\Ticket;
use App\Models\Trade;
use App\Models\TradeList;
use App\Models\User;
use App\Models\Withdrawal;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index(Request $request)
    {
        $response=[];
        $response['app_name']=optional(Setting::firstWhere('key','app_name'))->value;
        $response['app_logo']=optional(Setting::firstWhere('key','app_logo'))->value;



        $response['page_title']='لیست کاربران';

        $user=User::orderBy('id','DESC');

        $response['paginate_search'] = null;

        if (isset($request->name) && $request->name !== null)
        {
            $user=$user->where('name','LIKE','%'.$request->name.'%');

            session()->put('excell_name', $request->name);
            $response['user_name'] = $request->name;
        }


        if (isset($request->mobile) && $request->mobile !== null)
        {
            $user=$user->where('mobile','LIKE','%'.$request->mobile.'%');

            session()->put('excell_mobile', $request->mobile);
            $response['user_mobile']  =  $request->mobile;
        }

        if (isset($request->friendShip) && $request->friendShip !== null)
        {
            $user=$user->where('friendShip',$request->friendShip);

            session()->put('excell_friendShip', $request->friendShip);
            $response['user_friendShip'] = $request->friendShip;
        }


        $response['users']=$user->paginate(50);

        return view('admin.page.user.list',compact('response'));
    }

    public function show(User $user)
    {
        $response=[];
        $response['app_name']=optional(Setting::firstWhere('key','app_name'))->value;
        $response['app_logo']=optional(Setting::firstWhere('key','app_logo'))->value;

        $response['user']=$user;

        $response['ticket']=Ticket::where('user',$user->id)->orderBy('created_at','DESC')->paginate(20);

        $response['portfo'] = Portfo::where('user',$user->id)->orderBy('id', 'DESC')->paginate(20);

        $response['openTrade'] = Portfo::where([['user',$user->id],['end_date',null]])->get()->pluck('id')->toArray();
        $response['page_title']='مشخصات  : '.$user->name;

        return view('admin.page.user.detail',compact('response'));
    }

    public function status(User $user)
    {
        if ($user->status==='active')
            $user->status='deactive';
         else
            $user->status='active';
        $user->save();
        return redirect()->back();
    }


    public function destroy(User $user)
    {
        /* delete from ticket */
        Ticket::where('user',$user->id)->delete();

        /* delete from portfo,trade,tradeList */
        $portfo = Portfo::where('user',$user->id)->get()->pluck('id')->toArray();
        Trade::whereIn('portfo',$portfo)->delete();
        TradeList::whereIn('portfo',$portfo)->delete();
        Portfo::where('user',$user->id)->delete();

        /* delete from withdrawal and pay */
        Withdrawal::where('user',$user->id)->delete();
        Pay::where('user',$user->id)->delete();

        /* delete selected user */
        $user->delete();

        return redirect()->back()->with('success','کاربر با موفقیت حذف گردید');
    }




    public function excell()
    {

        $excell_name = session()->get('excell_name');
        $excell_mobile = session()->get('excell_mobile');
        $excell_friendShip = session()->get('excell_friendShip');

        $user=User::orderBy('id','DESC');

        if (isset($excell_name) && $excell_name !== null)
        {
            $user = $user->where('name','LIKE','%'.$excell_name.'%');
        }

        if (isset($excell_mobile) && $excell_mobile !== null)
        {
            $user = $user->where('mobile','LIKE','%'.$excell_mobile.'%');
        }

        if (isset($excell_friendShip) && $excell_friendShip !== null)
        {
            $user = $user->where('friendShip',$excell_friendShip);
        }

        $users = $user->get();

        $customer_array[] = array('نام','کد ملی','موبایل','راه آشنایی',
                                  'شماره شبا','نام بانک','کیف پول',
                                  'تاریخ ثبت نام');
        foreach($users as $user)
        {
            if($user->friendShip === 'instagram')
                $frienShip = 'اینستاگرام';
            elseif($user->friendShip === 'telegram')
                $frienShip = 'تلگرام';
            elseif ($user->friendShip === 'aparat')
                $frienShip = 'آپارات';
            elseif($user->friendShip === 'website')
                $frienShip = 'وب سایت';
            elseif($user->friendShip === 'family')
                $frienShip = 'آشنایی قبلی';
            else
                $frienShip = 'راه های دیگر';


            $customer_array[] = array(
                'نام'        => $user->name,
                'کد ملی'     => $user->codemeli,
                'موبایل'     => $user->mobile,
                'راه آشنایی' => $frienShip,
                'شماره شبا'  => $user->sheba,
                'نام بانک'   => $user->bank,
                'کیف پول'    => $user->wallet,
                'تاریخ ثبت نام'=>jdate($user->created_at)->format('Y/m/d'),

            );
        }
        return Excel::download(new Export($customer_array), 'user.xlsx');
    }
}

app/Http/Controllers/User/HistoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\FinancialHistory;
use App\Models\Pledge;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class HistoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $response=[];
        $response['app_name']=optional(Setting::firstWhere('key','app_name'))->value;
        $response['app_logo']=optional(Setting::firstWhere('key','app_logo'))->value;


        $response['user']=User::firstWhere('id',Auth::user()->id);

        $response['page_title']='تاریخچه مالی';

        $response['wallet'] = Auth::user()->wallet;

        $response['history']=FinancialHistory::where([['user',Auth::user()->id],['key','wallet']])->orderBy('id','DESC')->paginate(15);

        return view('user.page.history.list',compact('response'));
    }




}

app/Http/Controllers/User/IndexController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\Setting;
use App\Models\Ticket;
use App\Models\Visit;
use Illuminate\Support\Facades\Auth;

class IndexController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $response = [];
        $response['app_name'] = optional(Setting::firstWhere('key', 'app_name'))->value;
        $response['app_logo'] = optional(Setting::firstWhere('key', 'app_logo'))->value;


        $response['page_title'] = 'داشبورد';


        $response['wallet'] = Auth::user()->wallet;

        $response['unread_message_count'] = Ticket::where([['status', 'user-answer'], ['user', Auth::user()->id]])->get()->count();

        $notification = Visit::where([['model', 'Notification'], ['ip', Auth::user()->id]])->get()->pluck('model_id');

        $response['notification_count'] = Notification::whereNotIn('id', $notification)->count();


        return view('user.page.dashboard.dashboard', compact('response'));
    }
}

resources/views/user/side/sidebar.blade.php
<!-- Sidebar -->
<ul class="sidebar navbar-nav p-0 m-0 sidebar-user-width sidebar-background ">


    <!-- NAME -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width pr-0 position-relative" href="#"
           id="pagesDropdown" role="button"
           data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-angle-down arrow-left mt-3 text-gold d-none d-xl-inline-block d-lg-inline-block"></i>

            <img
                src="{{isset(\Illuminate\Support\Facades\Auth::user()->avatar) ? url(\Illuminate\Support\Facades\Auth::user()->avatar) : url('app/img/avatar.jpg')}}"
                style="height: 40px"
                class="rounded-circle mx-2 mb-1">

            <span class="font-family-yekan font-size-13 text-black font-weight-bolder" style="display: inline!important;">
                     {{\Illuminate\Support\Facades\Auth::user()->name }}
            </span>

            <div class="mx-auto text-center">
                <span class="font-size-11 text-danger font-weight-bold d-none d-xl-inline-block d-lg-inline-block">
                    موجودی :
                </span>
                <span class="fa-num text-success font-size-11 font-weight-bold">
                   {{number_format($response['wallet'])}}
                    تومان
                </span>
            </div>

        </a>
        <div class="dropdown-menu p-0 m-2 position-static" aria-labelledby="pagesDropdown">
            <a href="{{route('user.user.edit')}}" class="nav-link text-right text-dark">
                <i class="fas fa-user text-gold"></i>
                <span class="font-family-yekan font-size-13 font-weight-bold">ویرایش مشخصات</span>
            </a>

            <a href="{{route('user.user.edit.password')}}" class="nav-link text-right text-dark">
                <i class="fas fa-lock text-gold"></i>
                <span class="font-family-yekan font-size-13 font-weight-bold">تغییر کلمه عبور</span>
            </a>
        </div>
    </li>


    <!-- WALLET -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width position-relative w-100"
           href="#"  data-toggle="dropdown">
            <i class="fas fa-wallet font-size-22 ml-1 text-success"></i>
            <span class="font-family-yekan font-size-12 font-weight-bold d-inline">
                   کیف پول
                <i class="fas fa-angle-down text-success arrow-left mt-1  d-none d-xl-inline-block d-lg-inline-block"></i>
            </span>

        </a>
        <div class="dropdown-menu p-0 m-2 position-static" aria-labelledby="pagesDropdown">

            <a href="https://keivangold.ir/user/wallet/create" class="nav-link text-right text-dark w-100  d-none">
                <i class="fas fa-plus text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">شارژ کیف پول</span>
            </a>

            <a href="{{route('user.withdrawal.create')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-money-check text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">درخواست برداشت وجه</span>
            </a>

            <a href="{{route('user.history')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-list text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">تاریخچه حساب</span>
            </a>

        </div>
    </li>


    <!-- DASHBOARD -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width w-100" href="{{route('user.dashboard')}}">
            <i class="fas fa-home font-size-22 ml-1 text-gold"></i>
            <span class="font-family-yekan font-size-12 font-weight-bold d-inline">
                داشبورد
            </span>
        </a>
    </li>


    <!-- NOTIFICATION -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width w-100"
           href="{{route('user.notification.list')}}">
            <i class="fas fa-bell font-size-22 ml-1 text-gold"></i>
            <span class="font-family-yekan font-size-12 font-weight-bold d-inline">
                اطلاعیه ها
            </span>
        </a>
    </li>


    <!-- TRADE -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width position-relative w-100" href="#"
           id="pagesDropdown" role="button"
           data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-chart-bar font-size-22 text-gold"></i>
            <span class="font-family-yekan font-size-12 font-weight-bold d-inline">
                معاملات نقدی
                <i class="fas fa-angle-down text-gold arrow-left mt-1  d-none d-xl-inline-block d-lg-inline-block"></i>
            </span>

        </a>
        <div class="dropdown-menu p-0 m-2 position-static" aria-labelledby="pagesDropdown">

            <hr class="my-0"/>
            <a href="{{route('user.portfo.list')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-layer-group text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">مشاهده پرتفو</span>
            </a>
            <a href="{{route('user.trade.tradeList')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-trademark text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">معاملات در جریان</span>
            </a>
            <a href="{{route('user.trade.video')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-graduation-cap text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">آموزش معاملات</span>
            </a>
        </div>
    </li>


    <!-- CHAT -->
    <li class="nav-item border-bottom">
        <a class="nav-link text-right text-dark menu-padding sidebar-width position-relative w-100" href="#"
           id="pagesDropdown" role="button"
           data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope font-size-22 ml-1 text-gold"></i>
            <span class="font-family-yekan font-size-12 font-weight-bold d-inline">
                درخواست پشتیبانی
                <i class="fas fa-angle-down text-gold arrow-left mt-1 d-none d-xl-inline-block d-lg-inline-block"></i>
            </span>

        </a>
        <div class="dropdown-menu p-0 m-2 position-static" aria-labelledby="pagesDropdown">

            <hr class="my-0"/>
            <a href="{{route('user.ticket.add')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-envelope text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">ایجاد درخواست جدید</span>
            </a>

            <a href="{{route('user.ticket.list')}}" class="nav-link text-right text-dark w-100">
                <i class="fas fa-list text-gold"></i>
                <span class="text-dark font-size-12 font-weight-bold d-inline">لیست درخواست ها</span>
            </a>
        </div>
    </li>

</ul>